/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    tenants: Tenant;
    vans: Van;
    media: Media;
    technicians: Technician;
    services: Service;
    territory: Territory;
    configurations: Configuration;
    'state-environmental': StateEnvironmental;
    owner_organizations: OwnerOrganization;
    courts: Court;
    'court-price-slot': CourtPriceSlot;
    refunds: Refund;
    payments: Payment;
    user: User1;
    bookings: Booking;
    managers: Manager;
    venues: Venue;
    offers: Offer;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    vans: {
      technician: 'technicians';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    vans: VansSelect<false> | VansSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    technicians: TechniciansSelect<false> | TechniciansSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    territory: TerritorySelect<false> | TerritorySelect<true>;
    configurations: ConfigurationsSelect<false> | ConfigurationsSelect<true>;
    'state-environmental': StateEnvironmentalSelect<false> | StateEnvironmentalSelect<true>;
    owner_organizations: OwnerOrganizationsSelect<false> | OwnerOrganizationsSelect<true>;
    courts: CourtsSelect<false> | CourtsSelect<true>;
    'court-price-slot': CourtPriceSlotSelect<false> | CourtPriceSlotSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    user: UserSelect<false> | UserSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    managers: ManagersSelect<false> | ManagersSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title?: string | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles?: ('super-admin' | 'owner' | 'manager' | 'technician')[] | null;
  name: string;
  profilePhoto?: (number | null) | Media;
  tenants?:
    | {
        tenant: number | Tenant;
        roles: ('tenant-admin' | 'tenant-viewer')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  email: string;
  profilePhoto?: (number | null) | Media;
  /**
   * Used for domain-based tenant handling
   */
  domain?: string | null;
  /**
   * Used for url paths, example: /tenant-slug/page-slug
   */
  slug: string;
  /**
   * If checked, logging in is not required to read. Useful for building public pages.
   */
  allowPublicRead?: boolean | null;
  /**
   * The Medusa Sales Channel ID associated with this tenant.
   */
  salesChannelId?: string | null;
  /**
   * Publishable API Key associated with this tenant.
   */
  publishableApiKey?: string | null;
  /**
   * The Nylas Grant ID associated with this tenant.
   */
  grant_id?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vans".
 */
export interface Van {
  id: number;
  vehicleId: string;
  /**
   * Enter the year and make (e.g., 2023 Mercedes Sprinter)
   */
  yearAndMake: string;
  /**
   * Enter the model and trim (e.g., 3501 LWB Extra high roof)
   */
  modelTrim: string;
  tireCapacity?: number | null;
  technician?: {
    docs?: (number | Technician)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technicians".
 */
export interface Technician {
  id: number;
  name: string;
  email: string;
  password: string;
  mobilePhone: number;
  twilioPhone?: number | null;
  profilePhoto?: (number | null) | Media;
  mobileTireVan?: (number | Van)[] | null;
  user?: string | null;
  grant_id?: string | null;
  calendar_id?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  tyre_type?: ('8' | '6' | '5' | '4' | '3' | '2' | '1') | null;
  price: number;
  duration?: string | null;
  discount?: number | null;
  service: 'Trip Charge' | 'Install' | 'Tires & Install' | 'Patch Repair' | 'Balance & Rotation' | 'Fees';
  territory_id: number | Territory;
  isRefundable?: ('Yes' | 'No') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "territory".
 */
export interface Territory {
  id: number;
  name: string;
  polygon: {
    lat: number;
    lng: number;
    id?: string | null;
  }[];
  properties?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  type?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configurations".
 */
export interface Configuration {
  id: number;
  territory: number | Territory;
  configuration_id: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "state-environmental".
 */
export interface StateEnvironmental {
  id: number;
  state: string;
  fees?:
    | {
        fee: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "owner_organizations".
 */
export interface OwnerOrganization {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  password_hash: string;
  calcom_org_id?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courts".
 */
export interface Court {
  id: number;
  venue: number | Venue;
  name: string;
  area: string;
  surface: 'turf' | 'mat' | 'clay' | 'concrete' | 'grass';
  sport_type: 'box_cricket' | 'football' | 'badminton' | 'tennis' | 'volleyball';
  max_players: number;
  calcom_member_id: string;
  calcom_event_type_id: string;
  rating: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  owner_org: number | OwnerOrganization;
  name: string;
  lat: number;
  lng: number;
  full_address: string;
  description?: string | null;
  rating?: number | null;
  calcom_team_id?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "court-price-slot".
 */
export interface CourtPriceSlot {
  id: number;
  court_id: number | Court;
  day_of_week: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
  start_time: string;
  end_time: string;
  price_per_hour: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: number;
  payment_id: number | Payment;
  amount: number;
  reason: string;
  refund_status: string;
  refunded_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  booking_id: number | Booking;
  user_id: number | User;
  amount: number;
  status: string;
  method: string;
  transaction_id: string;
  paid_at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  user_id: number | User;
  court_id: number | Court;
  start_date_time: string;
  end_date_time: string;
  status: string;
  calcom_booking_id?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user".
 */
export interface User1 {
  id: number;
  name: string;
  email: string;
  password_hash: string;
  phone: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "managers".
 */
export interface Manager {
  id: number;
  venue: number | Venue;
  name: string;
  email: string;
  phone: string;
  created_by: number | OwnerOrganization;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  venue_id: number | Venue;
  title: string;
  description?: string | null;
  offer_type?: string | null;
  discount_value?: number | null;
  min_booking_amount?: number | null;
  valid_from?: string | null;
  valid_to?: string | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'vans';
        value: number | Van;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'technicians';
        value: number | Technician;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'territory';
        value: number | Territory;
      } | null)
    | ({
        relationTo: 'configurations';
        value: number | Configuration;
      } | null)
    | ({
        relationTo: 'state-environmental';
        value: number | StateEnvironmental;
      } | null)
    | ({
        relationTo: 'owner_organizations';
        value: number | OwnerOrganization;
      } | null)
    | ({
        relationTo: 'courts';
        value: number | Court;
      } | null)
    | ({
        relationTo: 'court-price-slot';
        value: number | CourtPriceSlot;
      } | null)
    | ({
        relationTo: 'refunds';
        value: number | Refund;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'user';
        value: number | User1;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'managers';
        value: number | Manager;
      } | null)
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  name?: T;
  profilePhoto?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  profilePhoto?: T;
  domain?: T;
  slug?: T;
  allowPublicRead?: T;
  salesChannelId?: T;
  publishableApiKey?: T;
  grant_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vans_select".
 */
export interface VansSelect<T extends boolean = true> {
  vehicleId?: T;
  yearAndMake?: T;
  modelTrim?: T;
  tireCapacity?: T;
  technician?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technicians_select".
 */
export interface TechniciansSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  password?: T;
  mobilePhone?: T;
  twilioPhone?: T;
  profilePhoto?: T;
  mobileTireVan?: T;
  user?: T;
  grant_id?: T;
  calendar_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  tyre_type?: T;
  price?: T;
  duration?: T;
  discount?: T;
  service?: T;
  territory_id?: T;
  isRefundable?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "territory_select".
 */
export interface TerritorySelect<T extends boolean = true> {
  name?: T;
  polygon?:
    | T
    | {
        lat?: T;
        lng?: T;
        id?: T;
      };
  properties?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "configurations_select".
 */
export interface ConfigurationsSelect<T extends boolean = true> {
  territory?: T;
  configuration_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "state-environmental_select".
 */
export interface StateEnvironmentalSelect<T extends boolean = true> {
  state?: T;
  fees?:
    | T
    | {
        fee?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "owner_organizations_select".
 */
export interface OwnerOrganizationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  password_hash?: T;
  calcom_org_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courts_select".
 */
export interface CourtsSelect<T extends boolean = true> {
  venue?: T;
  name?: T;
  area?: T;
  surface?: T;
  sport_type?: T;
  max_players?: T;
  calcom_member_id?: T;
  calcom_event_type_id?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "court-price-slot_select".
 */
export interface CourtPriceSlotSelect<T extends boolean = true> {
  court_id?: T;
  day_of_week?: T;
  start_time?: T;
  end_time?: T;
  price_per_hour?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  payment_id?: T;
  amount?: T;
  reason?: T;
  refund_status?: T;
  refunded_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  booking_id?: T;
  user_id?: T;
  amount?: T;
  status?: T;
  method?: T;
  transaction_id?: T;
  paid_at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_select".
 */
export interface UserSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  password_hash?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  user_id?: T;
  court_id?: T;
  start_date_time?: T;
  end_date_time?: T;
  status?: T;
  calcom_booking_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "managers_select".
 */
export interface ManagersSelect<T extends boolean = true> {
  venue?: T;
  name?: T;
  email?: T;
  phone?: T;
  created_by?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  owner_org?: T;
  name?: T;
  lat?: T;
  lng?: T;
  full_address?: T;
  description?: T;
  rating?: T;
  calcom_team_id?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  venue_id?: T;
  title?: T;
  description?: T;
  offer_type?: T;
  discount_value?: T;
  min_booking_amount?: T;
  valid_from?: T;
  valid_to?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}